### ISSUE TITLE
Add to chrome store?

### ISSUE THREAD

**Issue by kentcdodds** [DrewML/GifHub#1]
Any plans to do this eventually?

**Comment by DrewML** [comment]
Yep! Going to upload it tomorrow :)

**Comment by DrewML** [comment]
**[Published!](https://chrome.google.com/webstore/detail/gifhub/lponagpckglibniamicamklhfkoebpeb/)**
![spongebob-spongebob-squarepants-nickelodeon-plankton-elbwkxVuAfGiQ](https://camo.githubusercontent.com/48a0c6b068acd2c597bb6264a32b566a7cc6aaa9/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f656c62776b78567541664769512f67697068792e676966)
