### ISSUE TITLE
Popup not closing on outside click

### ISSUE THREAD

**Issue by DrewML** [DrewML/GifHub#11]
TODO:
- Determine why outer click isn't closing popup for some users
- Close popup on esc key

Ref: https://github.com/DrewML/GifHub/issues/9#issuecomment-205062510

**Comment by DrewML** [comment]
Added support to close with esc key in c72e981 (Released to Chrome store as 1.0.4).

Leaving this open until I can get more details about Kent's issue from #9.

**Comment by DrewML** [comment]
@kentcdodds has this been working for you?

**Comment by kentcdodds** [comment]
It's working! :D

**Comment by kentcdodds** [comment]
![news-atl-down-MTclfCr4tVgis](https://camo.githubusercontent.com/4d3cd1ddfffe47b0ab4028171dd6bb0642e286d7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d54636c6643723474566769732f67697068792e676966)

**Comment by DrewML** [comment]
![calls-then-casting-NENKWiQoPJqo](https://camo.githubusercontent.com/8d5d5898df4bcb1e6e0403d7daba0138bad9a444/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4e454e4b5769516f504a716f2f67697068792e676966)
