### ISSUE TITLE
Button doesn't show when editing existing comment in diff

### ISSUE THREAD

**Issue by DrewML** [DrewML/GifHub#12]
![image](https://cloud.githubusercontent.com/assets/5233399/14267307/d7f7a3c0-fa94-11e5-94a6-c65d3fdb0cb4.png)

**Comment by paulmolluzzo** [comment]
I just tested tried to replicate this and it looks right to me. Can you confirm?

**Comment by DrewML** [comment]
Thanks for looking! It took me awhile to catch it, but it looks like it happens when you add a new comment to the page, and then try to edit that comment. It makes sense, since I'm only injecting the buttons on page load, or partial navigations.

**Comment by DrewML** [comment]
~~Ha, now that I've said that, I can't replicate it.~~ Anddd replicated it.

**Comment by paulmolluzzo** [comment]
![6HOkD1pSCne4E](https://camo.githubusercontent.com/11d798873d6821a9479e81f8aae1f50543a20b0d/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f36484f6b44317053436e6534452f67697068792e676966)
