### ISSUE TITLE
Isn't working anymore

### ISSUE THREAD

**Issue by stefanbuck** [DrewML/GifHub#13]
In the console the following error appears. 

```
Uncaught TypeError: $ is not a function
```

Looks like GitHub dropped jQuery, at least from the window object.

Btw. Great extension 👍

**Comment by DrewML** [comment]
Good catch! Looks like they definitely dropped the global. Think I can still get at it with the global `require`, or just switch to vanilla DOM APIs. Will try to get a fix in for this tomorrow when I have some free time after work.

**Comment by DrewML** [comment]
Made an ugly (but functional) hack for now until I have the time to do a proper fix. Pushed the updated version (1.0.6) to the Chrome store. You should be able to force an update in 30 minutes - 1 hour by clicking "Update Extensions Now" in `chrome://extensions`

Thanks again for pointing that out!
