### ISSUE TITLE
Breaks JS on GitLab

### ISSUE THREAD

**Issue by DrewML** [DrewML/GifHub#14]
Reported in the Chrome store:

> Mike Koch Modified 2 days ago
> 
> This breaks JavaScript in GitLab. I'm honestly not sure why this extension needs access to all of my sites, when it only needs access to github.com (unless the user is using GH Enterprise)

**Comment by DrewML** [comment]
Fixed in `1.0.7`.

**Comment by evansantos** [comment]
This was a pain in my ass :(

But thank you to correct this! =D
