### ISSUE TITLE
Need an icon?

### ISSUE THREAD

**Issue by c9n** [DrewML/GifHub#2]
![funny-I4zybQwsOoqUE](https://camo.githubusercontent.com/d8585bf670333e93aeb0486903cc9cdc2ddf3a8b/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f49347a79625177734f6f7155452f67697068792e676966)

**Comment by DrewML** [comment]
An icon would be awesome! If you're willing to contribute that, I sure would appreciate it :)

My _only_ suggestion would be to avoid usage of the GitHub logo in it, per [this](https://github.com/logos).
![editingandlayout-the-office-thank-you-michael-scott-5xtDarmwsuR9sDRObyU](https://camo.githubusercontent.com/23f50e532a56551435cc7d3dc17b1113b161ce44/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f3578744461726d77737552397344524f6279552f67697068792e676966)

**Comment by tobiasbueschel** [comment]
Just to follow up with this issue, have you had a chance to look into making an icon? @c9n :)
