### ISSUE TITLE
Scrollbars - wrong width and height

### ISSUE THREAD

**Issue by djhvscf** [DrewML/GifHub#5]
See this screenshot: 
![capture](https://cloud.githubusercontent.com/assets/4496763/13781398/ce425aee-ea88-11e5-9d90-ac32ff068434.PNG)

Using: Chrome Version 48.0.2564.116

**Comment by DrewML** [comment]
Thanks for the report, @djhvscf!

I'm able to replicate that issue when I set "Show scroll bars" to "Always" in OSX. I'll push a fix a bit later today.

**Comment by DrewML** [comment]
Just pushed a fix to the Chrome Store (1.0.2). When using the "Always" scroll setting in OSX, the main window should look like this, now:

![image](https://cloud.githubusercontent.com/assets/5233399/13791132/aa9826b0-eab9-11e5-807a-910635c9f508.png)

Let me know if you have any problems. You should be able to hit "Update Extensions Now" in `chrome://extensions` in about 30 minutes to force an update.
