### ISSUE TITLE
Doesn't work with Refined Github

### ISSUE THREAD

**Issue by paulmolluzzo** [DrewML/GifHub#6]
This is neat, but because you're putting the button where the markdown helpers are the [Refined GitHub](https://github.com/sindresorhus/refined-github/) extension makes this extension non-functional. You can fix this by putting the button someplace else in the DOM to recreate the effect without making it a child of `.toolbar-commenting`.

**Comment by DrewML** [comment]
Haha yeah - I noticed this the other day when I first installed `Refined GitHub`. I'll find a place that doesn't look too awkward and push an update soon.
