### ISSUE TITLE
Focus!

### ISSUE THREAD

**Issue by paulmolluzzo** [DrewML/GifHub#9]
When you click the icon it should focus the text cursor in the search field. Every time I click I type something and wonder if my keyboard is broken. 😢

**Comment by DrewML** [comment]
Yeah, this is all kinds of necessary. I originally attempted to implement it when I first built the extension, but I ran into some strange issue that seemed related to Chrome. Happy to take a look at it again, or accept a PR with the change.

**Comment by kentcdodds** [comment]
Related, but likely a different issue: If I open it, then change my mind and decide to not add a gif, there's no way to close the popup... No matter where I click, it stays. :-(

**Comment by DrewML** [comment]
@kentcdodds Yeah, I noticed that the other day (but it's sporadic for me - works sometimes), but didn't have enough motivation at the time to fix it :P. Will knock it out at the same time as the `focus` issue.

**Comment by DrewML** [comment]
@kentcdodds What OS + version of Chrome? And is it hit and miss for you, or fairly consistent?

**Comment by paulmolluzzo** [comment]
@DrewML @kentcdodds may I suggest breaking that into a new issue to make it easier to discuss and fix?

@DrewML re: the focus, I already gave it a shot and had trouble focusing on the element even just by plopping a very specific `focus()` action on the hard coded element. If I get a chance I'll give it another shot.

**Comment by DrewML** [comment]
@paulmolluzzo Thanks for taking a look - makes me feel more sane that it wasn't just me missing something obvious.

@kentcdodds opened #11 for tracking

**Comment by DrewML** [comment]
Fix is in master - ~~will publish to the Chrome store in a bit (hoping to get #11 fixed right now so I can do 1 publish for both).~~ Published as `1.0.4`
